### PR TITLE
freebsd-relayd: Update ifdefs for SO_SPLICE support

### PR DESCRIPTION
**Pull request by markjdb**
relayd is a useful vehicle for testing SO_SPLICE. Start compiling splice support by default when compiled against a tree that implements SO_SPLICE. See https://reviews.freebsd.org/D46411 for a bit more background.

I did some basic testing to verify that TCP and HTTP proxying with SO_SPLICE works properly.

### CODE REVIEW

**Comment by 0mp** [comment]
Hey Mark! Thanks for the patch. It's great to see the splicing in FreeBSD relayd emerging.

I'd have one suggestion. Would it make sense to leave mark those lines are FreeBSD-specific? I am trying to have a clear indication if a line is a FreeBSD-specific patch by following this style: https://github.com/KlaraSystems/freebsd-relayd?tab=readme-ov-file#style. So I'd like to suggest we use either `/* BEGIN FreeBSD-relayd */` and `/* END FreeBSD-relayd */` comments or turn `#ifdef SO_SPLICE` into something along the lines of `#if !defined(__FreeBSD__) || SO_SPLICE`.

What are you thoughts about that?

**Comment by markjdb** [comment]
> Hey Mark! Thanks for the patch. It's great to see the splicing in FreeBSD relayd emerging.
> 
> I'd have one suggestion. Would it make sense to leave mark those lines are FreeBSD-specific? I am trying to have a clear indication if a line is a FreeBSD-specific patch by following this style: https://github.com/KlaraSystems/freebsd-relayd?tab=readme-ov-file#style. So I'd like to suggest we use either `/* BEGIN FreeBSD-relayd */` and `/* END FreeBSD-relayd */` comments or turn `#ifdef SO_SPLICE` into something along the lines of `#if !defined(__FreeBSD__) || SO_SPLICE`.
> 
> What are you thoughts about that?

I updated the patch to use `#if !defined(__FreeBSD__) || defined(SO_SPLICE)` everywhere. Adding comments around each preprocessor directive felt a bit excessive.

**Comment by 0mp** [comment]
Thanks!

**Comment by 0mp** [comment]
I've tagged a new release: https://github.com/KlaraSystems/freebsd-relayd/releases/tag/7.4.2024.01.15-p2

**Comment by 0mp** [comment]
New release: https://github.com/KlaraSystems/freebsd-relayd/releases/tag/7.4.2024.01.15-p2

**Comment by markjdb** [comment]
> New release: https://github.com/KlaraSystems/freebsd-relayd/releases/tag/7.4.2024.01.15-p2

Thank you!

**Pull request merged**
